import type { Metadata } from "next";
import { Noto_Sans } from 'next/font/google'
import "./globals.css";
import { FilterProvider } from "@/context/FilterContext";
import { ListProvider } from "@/context/ListContext";

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-noto-sans"
})

export const metadata: Metadata = {
  title: "Browser Extension Manager",
  description: "Generated by elo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`
        bg-linear-to-b 
        from-[#EBF2FC] 
        to-[#EEF8F9]
        flex flex-col 
        items-center 
        justify-center 
        dark:bg-linear-to-b 
        dark:from-[#040918] 
        dark:to-[#091540]
        bg-fixed
        py-8 p-4
        ${notoSans.className}`}>
        <FilterProvider>
          <ListProvider>
            {children}
          </ListProvider>
        </FilterProvider>
      </body>
    </html>
  );
}
